version: "3.4"

services:

  py-srv:
    build:
      context: py-srv
    ports:
      - 80:8000
    healthcheck:
      test: "exit 0"

  py-test-srv-pytest:
    build: py-test-srv/pytest
    volumes:
     - ./reports:/app/allure-report
   
  py-test-srv-testify:
    build:
      context: py-test-srv/testify
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=py-srv:8000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"
